blank_issues_enabled: true

contact_links:
  - name: Have you read the tutorials?
    url: https://github.com/open-telemetry/opentelemetry-go-compile-instrumentation/blob/main/README.md
    about: Much help can be found in the docs
