name: Check License Headers

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "license.yml"
      - ".github/workflows/check-license-headers.yaml"
  pull_request:
    paths:
      - "**/*.go"
      - "license.yml"
      - ".github/workflows/check-license-headers.yaml"

permissions:
  contents: read

jobs:
  check-license-headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod

      - name: Check License Headers
        run: make lint/license
