name: Check License Headers

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/*.sh"
      - "Makefile"
      - ".github/workflows/check-license-headers.yaml"
  pull_request:
    paths:
      - "**/*.go"
      - "**/*.sh"
      - "Makefile"
      - ".github/workflows/check-license-headers.yaml"

permissions:
  contents: read

jobs:
  check-license-headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - run: make lint/license-header

  done:
    name: Done (Check License Headers)
    runs-on: ubuntu-latest
    needs: [check-license-headers]
    if: always()
    steps:
      - name: Check result
        run: |
          echo ${{ needs.check-license-headers.result }}
          if [ "${{ needs.check-license-headers.result }}" = "success" ] || [ "${{ needs.check-license-headers.result }}" = "skipped" ]; then
            exit 0
          else
            exit 1
          fi
