name: Check Makefiles

on:
  push:
    branches:
      - main
    paths:
      - "**/*Makefile*"
      - ".github/config/checkmake"
      - ".github/workflows/checkmake.yaml"
  pull_request:
    paths:
      - "**/*Makefile*"
      - ".github/config/checkmake"
      - ".github/workflows/checkmake.yaml"

jobs:
  checkmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # ratchet:actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # ratchet:actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install checkmake
        run: go install github.com/checkmake/checkmake/cmd/checkmake@latest

      - name: Run checkmake
        run: checkmake --config .github/config/checkmake Makefile
