name: Check License Headers

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/*.sh"
      - "Makefile"
      - ".github/workflows/check-license-headers.yaml"
  pull_request:
    paths:
      - "**/*.go"
      - "**/*.sh"
      - "Makefile"
      - ".github/workflows/check-license-headers.yaml"

permissions:
  contents: read

jobs:
  check-license-headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

      - name: Check License Headers
        run: make lint/license-header
