name: Check Makefiles

on:
  push:
    branches:
      - main
    paths:
      - "**/*Makefile*"
      - ".config/checkmake"
      - ".github/workflows/checkmake.yaml"
  pull_request:
    paths:
      - "**/*Makefile*"
      - ".config/checkmake"
      - ".github/workflows/checkmake.yaml"

jobs:
  checkmake:
    name: Check Makefile Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: "1.25"
      - run: go install github.com/checkmake/checkmake/cmd/checkmake@latest
      - run: checkmake --config .config/checkmake Makefile
