name: Check Dockerfiles

on:
  pull_request:
    paths:
      - '**/*Dockerfile*'
      - '.config/hadolint.yaml'
      - '.github/workflows/lint-dockerfile.yaml'
  push:
    branches:
      - main
    paths:
      - '**/*Dockerfile*'
      - '.config/hadolint.yaml'
      - '.github/workflows/lint-dockerfile.yaml'

permissions:
  contents: read

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf  # v3.3.0
        with:
          config: .config/hadolint.yaml
          failure-threshold: warning
          recursive: true
