name: Check Go Code
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '.config/golangci.yml'
      - '.github/workflows/lint-golang.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - '.config/golangci.yml'
      - '.github/workflows/lint-golang.yaml'

permissions:
  contents: read
env:
  # TODO: Configure dependabot or renovate to update this version.
  GOLANGCI_LINT_VERSION: v2.1.6

jobs:
  golangci-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601  # v9.1.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --config .config/golangci.yml

  done:
    name: Done (Check Go Code)
    runs-on: ubuntu-latest
    needs: [golangci-lint]
    if: always()
    steps:
      - name: Check result
        run: |
          echo ${{ needs.golangci-lint.result }}
          if [ "${{ needs.golangci-lint.result }}" = "success" ] || [ "${{ needs.golangci-lint.result }}" = "skipped" ]; then
            exit 0
          else
            exit 1
          fi
