name: Check Go Code
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '.golangci.yml'
      - '.github/workflows/lint-golang.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - '.golangci.yml'
      - '.github/workflows/lint-golang.yaml'

permissions:
  contents: read
env:
  # TODO: Configure dependabot or renovate to update this version.
  GOLANGCI_LINT_VERSION: v2.1.6

jobs:
  golangci-lint:
    name: Check Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Check Format
        run: |
          golangci-lint fmt --diff
      - name: Lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47  # v9.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
