name: Check Dockerfiles

on:
  pull_request:
    paths:
      - '**/*Dockerfile*'
      - '.config/hadolint.yaml'
      - '.github/workflows/lint-dockerfile.yaml'
  push:
    branches:
      - main
    paths:
      - '**/*Dockerfile*'
      - '.config/hadolint.yaml'
      - '.github/workflows/lint-dockerfile.yaml'

permissions:
  contents: read

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        with:
          config: .config/hadolint.yaml
          failure-threshold: warning
          recursive: true
