name: Integration Tests
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'
      - 'tool/**'
      - 'pkg/**'
      - 'test/**'
      - '.github/workflows/test-integration.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'
      - 'tool/**'
      - 'pkg/**'
      - 'test/**'
      - '.github/workflows/test-integration.yaml'
# Declare default permissions as read only.
permissions: read-all
jobs:
  test-integration-coverage:
    if: false  # temporary disable
    name: Coverage Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
      - run: make test-integration/coverage
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1

  test-integration:
    name: Integration Tests (go ${{ matrix.platform.os }} ${{ matrix.platform.arch }})
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: amd64
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.mod"
      - name: Build and test
        env:
          GOARCH: ${{ matrix.platform.arch }}
        run: make test-integration

  done:
    name: Done (Integration Tests)
    runs-on: ubuntu-latest
    needs: [test-integration]
    steps:
      - name: Success
        run: |
          echo ${{ needs.test-integration.result }}
          test ${{ needs.test-integration.result }} == "success"
