name: Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'
      - 'tool/**'
      - 'pkg/**'
      - 'test/**'
      - '.github/workflows/test-unit.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'
      - 'tool/**'
      - 'pkg/**'
      - 'test/**'
      - '.github/workflows/test-unit.yaml'
# Declare default permissions as read only.
permissions: read-all
jobs:
  test-unit-coverage:
    if: false  # temporary disable
    name: Coverage Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
      - name: Run unit test coverage
        run: make test-unit/coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1

  test-unit:
    name: Unit Tests (go ${{ matrix.platform.os }} ${{ matrix.platform.arch }})
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: amd64
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.mod"
      - name: Build and test
        env:
          GOARCH: ${{ matrix.platform.arch }}
        run: make test-unit

  done:
    name: Done (Unit Tests)
    runs-on: ubuntu-latest
    needs: [test-unit]
    steps:
      - name: Success
        run: |
          echo ${{ needs.test-unit.result }}
          test ${{ needs.test-unit.result }} == "success"
